dist: trusty
sudo: required

language: go

go_import_path: github.com/aptly-dev/aptly

addons:
  apt:
    packages:
    - python-virtualenv
    - graphviz

env:
  global:
    - secure: "EcCzJsqQ3HnIkprBPS1YHErsETcb7KQFBYEzVDE7RYDApWeapLq+r/twMtWMd/fkGeLzr3kWSg7nhSadeHMLYeMl9j+U7ncC5CWG5NMBOj/jowlb9cMCCDlmzMoZLAgR6jm1cJyrWCLsWVlv+D0ZiB0fx4xaBZP/gIr9g6nEwC8="
    - secure: "OxiVNmre2JzUszwPNNilKDgIqtfX2gnRSsVz6nuySB1uO2yQsOQmKWJ9cVYgH2IB5H8eWXKOhexcSE28kz6TPLRuEcU9fnqKY3uEkdwm7rJfz9lf+7C4bJEUdA1OIzJppjnWUiXxD7CEPL1DlnMZM24eDQYqa/4WKACAgkK53gE="
    - NO_FTP_ACCESS: "yes"
    - BOTO_CONFIG: /dev/null

matrix:
  allow_failures:
    - go: master
      env: RUN_LONG_TESTS=no
  fast_finish: true
  include:
    - go: 1.8.x
      env: RUN_LONG_TESTS=no
    - go: 1.9.x
      env: RUN_LONG_TESTS=yes
    - go: 1.10.x
      env:
        - RUN_LONG_TESTS=yes
        - DEPLOY_BINARIES=yes
    - go: master
      env: RUN_LONG_TESTS=no

before_install:
  - virtualenv system/env
  - . system/env/bin/activate
  - pip install six packaging appdirs
  - pip install -U pip setuptools
  - pip install -r system/requirements.txt
  - make version

install:
  - make prepare

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks:
    urls:
      - "https://webhooks.gitter.im/e/c691da114a41eed6ec45"
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

before_deploy:
  - make nightly

deploy:
  provider: releases
  api_key:
    - secure: "MMk5S1Im6RrVudZasjtlCJa/rvRp4oavrR86WI2kQszs1iZIcdGyVhHiOGfWTwMjA/3iPdbAdu/WrjxCwI14GC5ws+rs8ICO6JIZktjtAwlfwlrV+nsrCiYx1EThghq43VEcykgz2UAJoJj/egv+UCEpe8yDTsvJ6we5HiXdTw0="
  file_glob: true
  file: build/*
  skip_cleanup: true
  on:
    tags: true
    condition: "$DEPLOY_BINARIES = yes"
